require 'uri'
require 'net/http'
require 'json'

require 'social_oauth_api/version'
require 'social_oauth_api/base'
require 'social_oauth_api/user'
require 'social_oauth_api/baidu/baidu'
require 'social_oauth_api/qqdenglu/qqdenglu'
require 'social_oauth_api/qqweibo/qqweibo'
require 'social_oauth_api/renren/renren'
require 'social_oauth_api/sinaweibo/sinaweibo'