require 'uri'
require 'net/http'
require 'json'

require 'social_oauth_api/version'
require 'social_oauth_api/base'
require 'social_oauth_api/social/sina_weibo'
require 'social_oauth_api/social/qq_denglu'
require 'social_oauth_api/social/qq_weibo'
require 'social_oauth_api/social/baidu'
require 'social_oauth_api/social/renren'