require 'uri'
require 'net/http'
require 'json'

require '../lib/social_oauth_api/version'
require '../lib/social_oauth_api/base'
require '../lib/social_oauth_api/user'
require '../lib/social_oauth_api/baidu/baidu'
require '../lib/social_oauth_api/qqdenglu/qqdenglu'
require '../lib/social_oauth_api/qqweibo/qqweibo'
require '../lib/social_oauth_api/renren/renren'
require '../lib/social_oauth_api/sinaweibo/sinaweibo'